# Generated by Django 6.0.1 on 2026-01-30 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_session_alter_document_filename_document_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rag.session'),
        ),
    ]
