# Generated by Django 6.0.1 on 2026-02-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_alter_document_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
