# Generated by Django 6.0.1 on 2026-02-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_document_abstract_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
