# Generated by Django 6.0.1 on 2026-02-09 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_document_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(help_text='Page number (1-indexed)')),
                ('start_offset', models.IntegerField(help_text='Start character offset in page text')),
                ('end_offset', models.IntegerField(help_text='End character offset in page text')),
                ('text', models.TextField(help_text='Highlighted text from document')),
                ('note', models.TextField(blank=True, help_text="User's personal note on this highlight")),
                ('tags', models.JSONField(default=list, help_text='List of string tags for categorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='Document being annotated', on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='rag.document')),
            ],
            options={
                'ordering': ['document', 'page', 'start_offset'],
            },
        ),
        migrations.CreateModel(
            name='HighlightEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_id', models.CharField(help_text="ChromaDB document ID for this highlight's embedding", max_length=255, unique=True)),
                ('embedded_at', models.DateTimeField(auto_now_add=True)),
                ('highlight', models.OneToOneField(help_text='Highlight that was embedded', on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='rag.highlight')),
            ],
        ),
        migrations.CreateModel(
            name='PaperSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('arxiv', 'arXiv'), ('pubmed', 'PubMed'), ('doi', 'DOI'), ('manual', 'Manual Upload')], max_length=20)),
                ('external_id', models.CharField(help_text='arXiv ID (e.g., 2411.04920v4), PubMed ID, DOI, etc.', max_length=255)),
                ('title', models.TextField()),
                ('authors', models.TextField(help_text='Comma-separated author names')),
                ('abstract', models.TextField(blank=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=500)),
                ('entry_url', models.URLField(blank=True, help_text='Link to paper page (arXiv abstract, PubMed entry, etc.)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported', models.BooleanField(default=False, help_text='Whether the PDF was successfully imported as a Document')),
                ('document', models.OneToOneField(blank=True, help_text='Linked document after successful import', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_source', to='rag.document')),
            ],
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Question text (denormalized for query even if Question deleted)')),
                ('mode', models.CharField(choices=[('qa', 'Question Answering'), ('compare', 'Compare Papers'), ('lit_review', 'Literature Review')], default='qa', help_text='RAG mode used for this query', max_length=20)),
                ('sources', models.JSONField(default=list, help_text='List of document filenames used as filters (empty = all docs)')),
                ('latency_ms', models.IntegerField(help_text='End-to-end query latency in milliseconds')),
                ('retrieved_chunks', models.JSONField(help_text='List of retrieved chunks with metadata: [{doc, page, chunk_id, score, text_preview}]')),
                ('prompt_tokens', models.IntegerField(blank=True, help_text='Number of tokens in prompt (if tracked)', null=True)),
                ('completion_tokens', models.IntegerField(blank=True, help_text='Number of tokens in completion (if tracked)', null=True)),
                ('error_type', models.CharField(blank=True, help_text='Error class name if query failed', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Full error message/traceback', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, help_text='Question model if created (nullable for eval runs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_logs', to='rag.question')),
                ('session', models.ForeignKey(help_text='Session in which query was executed', on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='rag.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['document', 'page'], name='rag_highlig_documen_f9bc99_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['created_at'], name='rag_highlig_created_df3528_idx'),
        ),
        migrations.AddIndex(
            model_name='highlightembedding',
            index=models.Index(fields=['embedding_id'], name='rag_highlig_embeddi_3c87fa_idx'),
        ),
        migrations.AddIndex(
            model_name='papersource',
            index=models.Index(fields=['source_type', 'external_id'], name='rag_paperso_source__38ec4e_idx'),
        ),
        migrations.AddIndex(
            model_name='papersource',
            index=models.Index(fields=['imported'], name='rag_paperso_importe_90003b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='papersource',
            unique_together={('source_type', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='runlog',
            index=models.Index(fields=['session', 'created_at'], name='rag_runlog_session_71da29_idx'),
        ),
        migrations.AddIndex(
            model_name='runlog',
            index=models.Index(fields=['mode'], name='rag_runlog_mode_09b60e_idx'),
        ),
    ]
