# Generated by Django 6.0.1 on 2026-02-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0006_document_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('arxiv', 'arXiv'), ('pubmed', 'PubMed'), ('doi', 'DOI'), ('manual', 'Manual Upload')], max_length=20)),
                ('external_id', models.CharField(help_text='arXiv ID (e.g., 2411.04920v4), PubMed ID, DOI, etc.', max_length=255)),
                ('title', models.TextField()),
                ('authors', models.TextField(help_text='Comma-separated author names')),
                ('abstract', models.TextField(blank=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=500)),
                ('entry_url', models.URLField(blank=True, help_text='Link to paper page (arXiv abstract, PubMed entry, etc.)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported', models.BooleanField(default=False, help_text='Whether the PDF was successfully imported as a Document')),
                ('document', models.OneToOneField(blank=True, help_text='Linked document after successful import', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_source', to='rag.document')),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'external_id'], name='rag_paperso_source__38ec4e_idx'), models.Index(fields=['imported'], name='rag_paperso_importe_90003b_idx')],
                'unique_together': {('source_type', 'external_id')},
            },
        ),
    ]
