# Generated by Django 6.0.1 on 2026-02-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0006_document_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
