# Generated by Django 6.0.1 on 2026-02-08 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0007_papersource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(help_text='Page number (1-indexed)')),
                ('start_offset', models.IntegerField(help_text='Start character offset in page text')),
                ('end_offset', models.IntegerField(help_text='End character offset in page text')),
                ('text', models.TextField(help_text='Highlighted text from document')),
                ('note', models.TextField(blank=True, help_text="User's personal note on this highlight")),
                ('tags', models.JSONField(default=list, help_text='List of string tags for categorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='Document being annotated', on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='rag.document')),
            ],
            options={
                'ordering': ['document', 'page', 'start_offset'],
            },
        ),
        migrations.CreateModel(
            name='HighlightEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_id', models.CharField(help_text="ChromaDB document ID for this highlight's embedding", max_length=255, unique=True)),
                ('embedded_at', models.DateTimeField(auto_now_add=True)),
                ('highlight', models.OneToOneField(help_text='Highlight that was embedded', on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='rag.highlight')),
            ],
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['document', 'page'], name='rag_highlig_documen_f9bc99_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['created_at'], name='rag_highlig_created_df3528_idx'),
        ),
        migrations.AddIndex(
            model_name='highlightembedding',
            index=models.Index(fields=['embedding_id'], name='rag_highlig_embeddi_3c87fa_idx'),
        ),
    ]
