# Generated by Django 6.0.1 on 2026-02-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0007_answer_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersource',
            name='source_type',
            field=models.CharField(choices=[('arxiv', 'arXiv'), ('pubmed', 'PubMed'), ('doi', 'DOI'), ('manual', 'Manual Upload'), ('acl', 'ACL Anthology'), ('medrxiv', 'medRxiv')], max_length=20),
        ),
    ]
