# Generated by Django 6.0.1 on 2026-03-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0008_alter_papersource_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='runlog',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Average retrieval confidence score (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='runlog',
            name='is_insufficient_evidence',
            field=models.BooleanField(default=False, help_text='Whether the LLM flagged insufficient evidence'),
        ),
        migrations.AddField(
            model_name='runlog',
            name='is_refusal',
            field=models.BooleanField(default=False, help_text='Whether the LLM response was a refusal (no relevant info found)'),
        ),
        migrations.AddField(
            model_name='runlog',
            name='retrieved_chunks_count',
            field=models.IntegerField(default=0, help_text='Number of chunks retrieved for this query'),
        ),
        migrations.AddIndex(
            model_name='runlog',
            index=models.Index(fields=['is_refusal'], name='rag_runlog_is_refu_ec7b9e_idx'),
        ),
    ]
