# Generated by Django 6.0.1 on 2026-02-08 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0008_highlight_highlightembedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Question text (denormalized for query even if Question deleted)')),
                ('mode', models.CharField(choices=[('qa', 'Question Answering'), ('compare', 'Compare Papers'), ('lit_review', 'Literature Review')], default='qa', help_text='RAG mode used for this query', max_length=20)),
                ('sources', models.JSONField(default=list, help_text='List of document filenames used as filters (empty = all docs)')),
                ('latency_ms', models.IntegerField(help_text='End-to-end query latency in milliseconds')),
                ('retrieved_chunks', models.JSONField(help_text='List of retrieved chunks with metadata: [{doc, page, chunk_id, score, text_preview}]')),
                ('prompt_tokens', models.IntegerField(blank=True, help_text='Number of tokens in prompt (if tracked)', null=True)),
                ('completion_tokens', models.IntegerField(blank=True, help_text='Number of tokens in completion (if tracked)', null=True)),
                ('error_type', models.CharField(blank=True, help_text="Error class name if query failed (e.g., 'ChromaConnectionError')", max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Full error message/traceback', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, help_text='Question model if created (nullable for eval runs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_logs', to='rag.question')),
                ('session', models.ForeignKey(help_text='Session in which query was executed', on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='rag.session')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='rag_runlog_session_71da29_idx'), models.Index(fields=['mode'], name='rag_runlog_mode_09b60e_idx'), models.Index(fields=['error_type'], name='rag_runlog_error_t_64b093_idx'), models.Index(fields=['created_at'], name='rag_runlog_created_b171bb_idx')],
            },
        ),
    ]
